package:
  name: awkward-cpp
  version: "42"
  top-level:
    - awkward_cpp

source:
  url: https://files.pythonhosted.org/packages/6b/71/5cd9fd9b2412e7e2c7e46201cecfd2145515947eaf81a5a2dd9d51b94cd6/awkward_cpp-42.tar.gz
  sha256: d6c489ecbe9ab2eaa34d45ccecec55b74807b363feca23b8d76dc8bc207355ec

build:
  exports: requested

requirements:
  run:
    - numpy

test:
  imports:
    - awkward_cpp

about:
  home: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - agoose77
